### ISSUE TITLE
Checkpoint w51-2018 (NAVIDAD)

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3#122]
Por hacer un pequeño repaso de cómo vamos y qué cosas van quedando pendientes....

**Semana 51 de 2018**

### :dart: Objetivos de este periodo

Ya estamos empezando con cosas más avanzadas del lenguaje y el objetivo hasta la clase 67 es ir adentrándonos en Node, Automatización, Funcionamiento interno de JavaScript, Dominar conceptos avanzados, Patrones, Arquitectura, HTML5 Apis, Firebase, autenticación, terminal... y muchas cosas más!

Las navidades son una de las mejores épocas del año para ponerse al día con el master y asentar todo lo que hemos visto hasta ahora, no perdáis este tren... 

### :books: Libros y charlas recomendadas para este periodo

**Libros Previos**
- [JavaScript, ¡Inspírate!](https://leanpub.com/javascript-inspirate)
- [Eloquent JavaScript de Marijn Haverbeke](https://eloquentjavascript.net/)

**Libros básicos**
- [You Don't Know JS: Up & Going de Kyle Simpson](https://github.com/getify/You-Dont-Know-JS/tree/master/up%20%26%20going)
- [You Don't Know JS: Types & Grammar de Kyle Simpson](https://github.com/getify/You-Dont-Know-JS/tree/master/types%20%26%20grammar)

**Libros más avanzados**
- [JavaScript: The Good Parts de Douglas Crockford](http://shop.oreilly.com/product/9780596517748.do)
- [Learning JavaScript Design Pattern de Addy Osmani](http://addyosmani.com/resources/essentialjsdesignpatterns/book/)

### :pushpin: Cosas pendientes
**Importante**
- [ ] [Crear un issue](https://github.com/Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3/issues/new) explicando vuestro proyecto y los retos que os plantea
- [ ] [Crear un repositorio](https://github.com/new) nuevo y utilizar [Gitflow](https://es.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) para trabajar en el nuevo proyecto
- [ ] Vovemos de vacaciones el día 9 de Enero (Miércoles)

**Retos**
- [x] ¿Serías capaz de entrar en [Hack the box](https://github.com/Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3/issues/121)?

**Oportunidades**
- [ ] [Apuntarse en Circular como candidat@](https://trycircular.com/accounts/candidate/signup-with-referral-request/) y pedir mi recomendación. *Puedes sacar mi email de la API de Github*
- [ ] La propuesta para [salvar Memezinga](https://github.com/Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3/issues/116) sigue sobre la mesa si tienes ganas de meterte en un proyecto intenso con un entorno exigente...

**Ejercicios**
- [ ] Ejercicio típico de entrevistas de trabajo `NASA Rover Challenge` en la [clase 25](https://github.com/Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3/blob/master/teoria/clase25.md#ejercicios)
- [ ] [Katas de ES6](http://es6katas.org/)
- [ ] Ejercicio del `Curiosity` para resolver llamadas Ajax recursivas usando promesas en la [clase 28](https://github.com/Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3/blob/master/teoria/clase28.md)
- [ ] Crea tu primera librería para gestionar llamadas ajax con `$http` en la [clase 29](https://github.com/Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3/blob/master/teoria/clase29.md)
- [ ] Crea una aplicación con Rutas + Templates + llamadas Ajax en la [Clase 30](https://github.com/Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3/blob/master/teoria/clase30.md)

**Otros**
- [ ] Mejores la [Colección de videos imperdibles de Youtube](https://github.com/Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3/issues/113)
- [ ] Ponte al día con la [cultura hacker](https://github.com/Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22%3Atophat%3A+Cultura+Hacker%22+)

### 🕒 Deadlines
- [ ] Clase 33 (11/01/19): Solucionamos 25-30

### :warning: Foco

- [ ] Trabajar en el segundo proyecto del Master que se entregará en la clase 67, [requisitos](https://github.com/Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed3/blob/master/teoria/clase23.md#nuevo-proyecto-personal)

**Comment by Fa-v** [comment]
Hola!

Estoy trabajando en el ejercicio de Buenos días, Madrid! :) y en la librería $http pero no funciona la url 'http://airemad.com/api/v1/station' 😢  no veo ningún error solo sale la página de unable to connect 😭 
 
![screenshot 2019-01-08 at 14 06 12](https://user-images.githubusercontent.com/19712816/50832474-9c2bbe00-134e-11e9-8400-6a2f90f3614a.png)

**Comment by KoolTheba** [comment]
@Fa-v !! Aquí en mi web de status verás cuando está bien o caída...sorry :( https://status.osweekends.com/

**Comment by KoolTheba** [comment]
@UlisesGascon !! Arreglanoslaaaaa

**Comment by Fa-v** [comment]
Que conste que una no puede terminar los deberes por eso 🤓 🤣

**Comment by UlisesGascon** [comment]
Ya esta funcionando de nuevo.. igual tenemos un apagón momentaneo esta semana porque  nos migramos de GCloud a la infraestructura de OSW, pero no deberían ser más de 5 minutos. Os aviso cuando sea ^^

**Comment by Fa-v** [comment]
Gracias! ❤️
